name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Environment Variables
        env:
          #These are github secrets.
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          
        run: |
          # Save the SSH private key and set the permissions
          echo "$SSH_PRIVATE_KEY" > KeyTwo.pem

          # Set read and write permissions for owner.
          chmod 600 KeyTwo.pem

      - name: Deploy to EC2
        run: |
          # Define EC2 instance details
          INSTANCE_ID="i-0455c1a7044a93abe" 

          # An elastic IP was allocated to the EC2 instance
          PUBLIC_IP=98.83.197.203 

          # SSH into the EC2 instance
          #StrictHostKeyChecking=no - command is required to disable identity verification of the server connection.

          ssh -o StrictHostKeyChecking=no -i KeyTwo.pem ubuntu@$PUBLIC_IP << 'EOF'
            # Exit if error occurs
            set -e
            # Navigate to Recipe App directory
            cd /home/ubuntu/CAD_CA1
            # Pull repository state to vm
            git pull origin master
            
            
            # Install dependencies, migrate the database, and Start the application
            
            bundle install
            rails db:migrate

            # When the application would start - the workflow would run until the rails server was terminated.
            #RAILS_ENV=production sudo /home/ubuntu/.rbenv/shims/rails server --binding 0.0.0.0 --port 80
          EOF

      - name: Clean up
        run: |
          # Remove the private key after use
          rm -f KeyTwo.pem