name: Deploy to AWS EC2

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Environment Variables
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          
        run: |
          # We know this script will be ran on and linux terminal, allows to create a KeyTwo.pem file by echoing the value kept as a gitgub secret. 
          # Save the SSH private key and set the permissions
          echo "$SSH_PRIVATE_KEY" > KeyTwo.pem
          chmod 600 KeyTwo.pem

      - name: Deploy to EC2
        run: |
          # Define the EC2 instance details
          INSTANCE_ID="i-0455c1a7044a93abe" 
          # An elastic IP was allocated to the EC2 instance
          PUBLIC_IP=98.83.197.203 

          # SSH into the EC2 instance
          ssh -o StrictHostKeyChecking=no -i KeyTwo.pem ubuntu@$PUBLIC_IP << 'EOF'
            # Exit if error occurs
            set -e
            # Navigate to pRecipe App directory
            cd /home/ubuntu/CAD_CA1
            # Pull repository state to vm
            git pull origin master
            
            # Kill the server if one is running
            pkill -f "rails server" || true
            
            # Install dependencies, migrate the database, and Start the application
            #When the application would start - the workflow would never finish
            bundle install
            rails db:migrate
            RAILS_ENV=production nohup sudo /home/ubuntu/.rbenv/shims/rails server --binding 0.0.0.0 --port 80
            pkill -f "rails server" || true
          EOF

      - name: Clean up
        run: |
          # Remove the private key after use
          rm -f KeyTwo.pem
